### ISSUE TITLE
Add presto/trino component into hadoop-testing

### ISSUE THREAD

**Issue by yanghua** [awesome-kyuubi/hadoop-testing#11]
As we all know, presto and trino both are popular AD-Hoc engines for the data warehouse and lakehouse in the Hadoop ecosystem. It's valuable to add them to the playground.

**Comment by pan3793** [comment]
SGTM, but I suppose you are intend to launch a dedicated container to launcher Trino rather than deploy them in the existing hadoop-master/worker nodes?

**Comment by yanghua** [comment]
> SGTM, but I suppose you are intend to launch a dedicated container to launcher Trino rather than deploy them in the existing hadoop-master/worker nodes?

Yes, a single container.

**Comment by pan3793** [comment]
TBH, I lean to deploy Trino manually into `hadoop-*` containers, one of the main purposes of this project is to emulate a production-like deployment, rather than something like [Hadoop pseudo-distributed mode](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-common/SingleCluster.html#Pseudo-Distributed_Operation), a multi-nodes environment has several benefits to help developers to experiment or learn a new component.

Given that, I would recommend deploying those components into `hadoop-*` containers which are usually mix-deployed with Hadoop node instead of running in an independent container. On the other hand, for S3, MySQL/RDS stuffs, which usually provided by public cloud venders or managed by DBA, are fine to run in an independent container

**Comment by yanghua** [comment]
Trino 436 requires JDK 21: https://trino.io/docs/current/release/release-436.html

And some recent versions all require JDK 11+, https://trino.io/blog/2023/11/03/java-21.html

@pan3793 What's your opinion?

**Comment by pan3793** [comment]
there is no impact if u want to run trino in an independent container.

if deploy trino in `hadoop-*` containers simply add a `/opt/openjdk-21` as we did for 8 and 17 now

**Comment by yanghua** [comment]
> there is no impact if u want to run trino in an independent container.
> 
> if deploy trino in `hadoop-*` containers simply add a `/opt/openjdk-21` as we did for 8 and 17 now

My thoughts:

* deploy coordinator -> hadoop-master1;
* deploy work1 -> hadoop-worker1;
* deploy work2 -> hadoop-worker2;
* deploy work3 -> hadoop-worker3;

**Comment by pan3793** [comment]
sgtm, let's add `/opt/openjdk-21` to base images first

**Comment by yanghua** [comment]
@pan3793 It seems I can not find the mirror URL from Tencent Maven Repository for https://repo1.maven.org/maven2/io/trino/trino-server/436/trino-server-436.tar.gz 

Any input?
